ARG PYTHON_VERSION=3.12.4
FROM docker-proxy.kontur.host/python:${PYTHON_VERSION}-slim AS base
ENV PYTHONDONTWRITEBYTECODE=1

# Keeps Python from buffering stdout and stderr to avoid situations where
# the application crashes without emitting any logs due to buffering.
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY /src src

COPY requirements.txt .

RUN python -m pip install -r requirements.txt

CMD cd src && python -m arq workers.notifications.WorkerSettings

