ARG PYTHON_VERSION=3.12.4
FROM docker-proxy.kontur.host/python:${PYTHON_VERSION}-slim as base
ENV PYTHONDONTWRITEBYTECODE=1

# Keeps Python from buffering stdout and stderr to avoid situations where
# the application crashes without emitting any logs due to buffering.
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY /src/workers workers

COPY /src/configs configs

COPY /src/database database

COPY /src/helpers helpers

COPY /src/handlers handlers

RUN python -m pip install -r workers/requirements.txt

CMD python -m arq workers.notifications.WorkerSettings

