"""migration1

Revision ID: 3038e5f0b999
Revises: 83af59a4d1f0
Create Date: 2024-04-06 10:39:15.056055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3038e5f0b999'
down_revision: Union[str, None] = '83af59a4d1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('action_type_key'), 'action', ['type'])
    op.add_column('category', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('category', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint(op.f('category_name_key'), 'category', ['name'])
    op.add_column('record', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('record', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('record', 'time')
    op.add_column('resource', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('resource', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('visitor', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('visitor', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visitor', 'updated_at')
    op.drop_column('visitor', 'created_at')
    op.drop_column('resource', 'updated_at')
    op.drop_column('resource', 'created_at')
    op.add_column('record', sa.Column('time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('record', 'updated_at')
    op.drop_column('record', 'created_at')
    op.drop_constraint(op.f('category_name_key'), 'category', type_='unique')
    op.drop_column('category', 'updated_at')
    op.drop_column('category', 'created_at')
    op.drop_constraint(op.f('action_type_key'), 'action', type_='unique')
    # ### end Alembic commands ###
