"""migration3_records

Revision ID: 4d418031dbae
Revises: d4411bf2c991
Create Date: 2024-12-18 16:12:19.563722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Connection, text
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import expression

# revision identifiers, used by Alembic.
revision: str = '4d418031dbae'
down_revision: Union[str, None] = 'd4411bf2c991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def update_take_and_enqueue_columns(connection: Connection) -> None:
    connection.execute(text("UPDATE record SET enqueue_date = created_at WHERE action = 'QUEUE'"))
    connection.execute(text("UPDATE record SET take_date = created_at WHERE action = 'TAKE'"))


def transfer_resource_id(connection: Connection) -> None:
    connection.execute(text("UPDATE record SET resource_id = resource"))


def transfer_address_and_return_date(connection: Connection) -> None:
    result = connection.execute(
        text(f'SELECT id, user_email, return_date, address FROM resource WHERE resource.user_email IS NOT NULL'))
    rows = result.fetchall()
    for row in rows:
        resource_id, user_email, return_date, address = row
        connection.execute(text(
            f"UPDATE record SET address='{address}', return_date='{return_date}' WHERE resource={resource_id} and record.user_email='{user_email}' and record.action='TAKE'"))

def update_data(connection: Connection) -> None:
    update_take_and_enqueue_columns(connection)
    transfer_address_and_return_date(connection)
    transfer_resource_id(connection)


def upgrade() -> None:
    op.add_column('record', sa.Column('resource_id', sa.Integer(), nullable=True))
    op.add_column('record', sa.Column('address', sa.String(), nullable=True))
    op.add_column('record', sa.Column('enqueue_date', sa.DateTime(), nullable=True))
    op.add_column('record', sa.Column('take_date', sa.DateTime(), nullable=True))
    op.add_column('record', sa.Column('return_date', sa.DateTime(), nullable=True))
    op.add_column('record', sa.Column('finished', sa.Boolean(), nullable=False, server_default=expression.false()))

    update_data(op.get_bind())

    op.alter_column('record', "resource_id", nullable=False)

    op.drop_constraint('record_action_action_fkey', 'record', type_='foreignkey')
    op.drop_column('record', 'action')
    op.drop_table('action')
    op.drop_constraint('record_resource_resource_fkey', 'record', type_='foreignkey')
    op.create_foreign_key(op.f('record_resource_id_resource_fkey'), 'record', 'resource', ['resource_id'], ['id'], onupdate='cascade', ondelete='cascade')
    op.drop_column('record', 'resource')
    op.drop_constraint('resource_user_email_visitor_fkey', 'resource', type_='foreignkey')
    op.drop_column('resource', 'address')
    op.drop_column('resource', 'user_email')
    op.drop_column('resource', 'return_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('return_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('resource_user_email_visitor_fkey', 'resource', 'visitor', ['user_email'], ['email'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('record', sa.Column('resource', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('record', sa.Column('action', postgresql.ENUM('TAKE', 'QUEUE', 'RETURN', 'LEAVE', 'EDIT', name='actiontype'), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('record_resource_id_resource_fkey'), 'record', type_='foreignkey')
    op.create_foreign_key('record_resource_resource_fkey', 'record', 'resource', ['resource'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('record_action_action_fkey', 'record', 'action', ['action'], ['type'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('record', 'finished')
    op.drop_column('record', 'return_date')
    op.drop_column('record', 'take_date')
    op.drop_column('record', 'enqueue_date')
    op.drop_column('record', 'address')
    op.drop_column('record', 'resource_id')
    op.create_table('action',
    sa.Column('type', postgresql.ENUM('TAKE', 'QUEUE', 'RETURN', 'LEAVE', 'EDIT', name='actiontype'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('type', name='action_pkey')
    )
    # ### end Alembic commands ###
