"""migration5_rollback_contsraint_for_record

Revision ID: a373c2729ea1
Revises: de8c7b942262
Create Date: 2025-02-20 17:18:19.217324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a373c2729ea1'
down_revision: Union[str, None] = 'de8c7b942262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_resource_visitor_uc', 'record', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_resource_visitor_uc', 'record', ['resource_id', 'user_email'])
    # ### end Alembic commands ###
