"""migration4_services

Revision ID: de8c7b942262
Revises: 4d418031dbae
Create Date: 2025-02-18 11:42:29.912216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de8c7b942262'
down_revision: Union[str, None] = '4d418031dbae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_resource_visitor_uc', 'record', ['resource_id', 'user_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_resource_visitor_uc', 'record', type_='unique')
    # ### end Alembic commands ###
